import type { InteractiveLesson } from '@/types';

export const additionLeftToRight: InteractiveLesson = {
  slug: 'addition-left-to-right',
  title: 'Add Left to Right',
  description: 'Forget carrying. Start from the biggest digits and build a running total.',
  category: 'addition',
  emoji: '\u27A1\uFE0F',
  difficulty: 1,
  sortOrder: 4,
  xpReward: 10,
  perfectBonus: 5,
  steps: [
    {
      type: 'teach',
      content: 'School taught you to add right-to-left. But for mental math, left-to-right is far more natural \u2014 you build a running total just like reading.',
      emoji: '\uD83E\uDDE0',
    },
    {
      type: 'teach',
      title: 'The Method',
      content: 'Start with the largest place value. Add each column left-to-right, keeping a running total. Adjust as you go.',
      formula: '467 + 385 \u2192 700 \u2192 840 \u2192 852',
    },
    {
      type: 'example',
      problem: '467 + 385',
      revealSteps: [
        'Hundreds: 400 + 300 = 700',
        'Tens: 60 + 80 = 140. Running total: 700 + 140 = 840',
        'Ones: 7 + 5 = 12. Running total: 840 + 12 = 852',
      ],
      finalAnswer: '852',
    },
    {
      type: 'quiz',
      question: 'Why is left-to-right better for mental math?',
      options: [
        'It gives a different answer',
        'You get an approximate answer immediately',
        'It uses fewer steps',
        'It avoids addition entirely',
      ],
      correctIndex: 1,
      explanation: 'Starting with the biggest digits gives you a ballpark answer right away, making mental tracking easier.',
    },
    {
      type: 'practice',
      prompt: 'What is 234 + 567?',
      operand1: 234,
      operand2: 567,
      operation: '+',
      answer: 801,
      hint: '200+500=700, 30+60=90 \u2192 790, 4+7=11 \u2192 801',
    },
    {
      type: 'practice',
      prompt: 'What is 678 + 453?',
      operand1: 678,
      operand2: 453,
      operation: '+',
      answer: 1131,
    },
    {
      type: 'teach',
      title: 'Works for Any Size',
      content: 'This method scales to 4-digit numbers and beyond. Just keep your running total updated as you move right.',
    },
    {
      type: 'example',
      problem: '1284 + 3917',
      revealSteps: [
        'Thousands: 1000 + 3000 = 4000',
        'Hundreds: 200 + 900 = 1100. Total: 5100',
        'Tens: 80 + 10 = 90. Total: 5190',
        'Ones: 4 + 7 = 11. Total: 5201',
      ],
      finalAnswer: '5201',
    },
    {
      type: 'practice',
      prompt: 'What is 845 + 376?',
      operand1: 845,
      operand2: 376,
      operation: '+',
      answer: 1221,
    },
    {
      type: 'practice',
      prompt: 'What is 1492 + 2638?',
      operand1: 1492,
      operand2: 2638,
      operation: '+',
      answer: 4130,
    },
    {
      type: 'quiz',
      question: 'Using left-to-right addition on 529 + 384, what is the running total after adding the hundreds?',
      options: ['900', '800', '1100', '500'],
      correctIndex: 1,
      explanation: '500 + 300 = 800. That\'s your starting point before you add the tens and ones.',
    },
  ],
};
