import type { InteractiveLesson } from '@/types';

export const multiplyBy11: InteractiveLesson = {
  slug: 'multiply-by-11',
  title: 'Multiply Any Number by 11',
  description: 'A dead-simple trick to multiply any two-digit number by 11 in your head.',
  category: 'multiplication',
  emoji: '\u26A1',
  difficulty: 1,
  sortOrder: 1,
  xpReward: 10,
  perfectBonus: 5,
  steps: [
    {
      type: 'teach',
      content: 'What if you could multiply any two-digit number by 11 in your head — instantly?',
      emoji: '\uD83E\uDDE0',
    },
    {
      type: 'teach',
      title: 'The Rule',
      content: 'Split the two digits apart, add them together, and place the sum in the middle.',
      formula: 'AB \u00D7 11 = A_(A+B)_B',
    },
    {
      type: 'example',
      problem: '36 \u00D7 11',
      revealSteps: [
        'Split the digits: 3 _ 6',
        'Add them: 3 + 6 = 9',
        'Place 9 in the middle: 3 [9] 6',
      ],
      finalAnswer: '396',
    },
    {
      type: 'quiz',
      question: 'When multiplying 54 \u00D7 11, what do you place in the middle?',
      options: ['9', '54', '11', '5'],
      correctIndex: 0,
      explanation: '5 + 4 = 9, so 54 \u00D7 11 = 594',
    },
    {
      type: 'practice',
      prompt: 'Your turn! What is 27 \u00D7 11?',
      operand1: 27,
      operand2: 11,
      operation: '\u00D7',
      answer: 297,
      hint: 'Split: 2 _ 7. Add: 2 + 7 = 9. Result: 297',
    },
    {
      type: 'practice',
      prompt: 'What is 63 \u00D7 11?',
      operand1: 63,
      operand2: 11,
      operation: '\u00D7',
      answer: 693,
    },
    {
      type: 'teach',
      title: 'What If the Sum Is 10 or More?',
      content: 'If the two digits add up to 10 or more, carry the 1 to the left digit. The middle digit is just the ones place of the sum.',
      formula: '85 \u00D7 11 \u2192 8+5=13 \u2192 (8+1)_3_5 = 935',
    },
    {
      type: 'example',
      problem: '85 \u00D7 11',
      revealSteps: [
        'Split the digits: 8 _ 5',
        'Add them: 8 + 5 = 13',
        'Place 3 in the middle, carry the 1',
        '(8 + 1) 3 5 = 935',
      ],
      finalAnswer: '935',
    },
    {
      type: 'quiz',
      question: 'What is 94 \u00D7 11?',
      options: ['1034', '9134', '944', '1044'],
      correctIndex: 0,
      explanation: '9 + 4 = 13. Carry the 1: (9+1)_3_4 = 1034',
    },
    {
      type: 'practice',
      prompt: 'Solve: 67 \u00D7 11',
      operand1: 67,
      operand2: 11,
      operation: '\u00D7',
      answer: 737,
      hint: '6 + 7 = 13. Carry the 1: 737',
    },
    {
      type: 'practice',
      prompt: 'Solve: 48 \u00D7 11',
      operand1: 48,
      operand2: 11,
      operation: '\u00D7',
      answer: 528,
    },
    {
      type: 'practice',
      prompt: 'Speed round! 72 \u00D7 11',
      operand1: 72,
      operand2: 11,
      operation: '\u00D7',
      answer: 792,
    },
    {
      type: 'quiz',
      question: 'Which step do you NOT do when multiplying by 11?',
      options: ['Split the digits apart', 'Multiply the digits together', 'Add the digits together', 'Place the sum in the middle'],
      correctIndex: 1,
      explanation: 'You add the digits, not multiply them!',
    },
  ],
};
