import type { InteractiveLesson } from '@/types';

export const squaringEnding5: InteractiveLesson = {
  slug: 'squaring-ending-5',
  title: 'Square Numbers Ending in 5',
  description: 'Instantly square any number ending in 5 with one simple pattern.',
  category: 'multiplication',
  emoji: '\u2B50',
  difficulty: 1,
  sortOrder: 2,
  xpReward: 10,
  perfectBonus: 5,
  steps: [
    {
      type: 'teach',
      content: 'Squaring 25, 35, or 75 in your head takes about two seconds with this trick.',
      emoji: '\u2728',
    },
    {
      type: 'teach',
      title: 'The Rule',
      content: 'Take the digit(s) before the 5, multiply by the next number up, then append 25.',
      formula: 'n5\u00B2 = n \u00D7 (n+1) | 25',
    },
    {
      type: 'example',
      problem: '25\u00B2',
      revealSteps: [
        'Digit before 5: 2',
        'Next number up: 3',
        'Multiply: 2 \u00D7 3 = 6',
        'Append 25: 625',
      ],
      finalAnswer: '625',
    },
    {
      type: 'quiz',
      question: 'What do you always append to the result?',
      options: ['5', '50', '25', '55'],
      correctIndex: 2,
      explanation: 'The answer always ends in 25!',
    },
    {
      type: 'practice',
      prompt: 'What is 35\u00B2?',
      operand1: 35,
      operand2: 35,
      operation: '\u00D7',
      answer: 1225,
      hint: '3 \u00D7 4 = 12, append 25 \u2192 1225',
    },
    {
      type: 'practice',
      prompt: 'What is 45\u00B2?',
      operand1: 45,
      operand2: 45,
      operation: '\u00D7',
      answer: 2025,
    },
    {
      type: 'teach',
      title: 'Works for Bigger Numbers Too',
      content: 'The same trick works for 3-digit numbers. Just take everything before the 5.',
      formula: '115\u00B2 \u2192 11 \u00D7 12 = 132 \u2192 13225',
    },
    {
      type: 'example',
      problem: '85\u00B2',
      revealSteps: [
        'Digit before 5: 8',
        'Next number up: 9',
        'Multiply: 8 \u00D7 9 = 72',
        'Append 25: 7225',
      ],
      finalAnswer: '7225',
    },
    {
      type: 'practice',
      prompt: 'What is 75\u00B2?',
      operand1: 75,
      operand2: 75,
      operation: '\u00D7',
      answer: 5625,
    },
    {
      type: 'practice',
      prompt: 'What is 95\u00B2?',
      operand1: 95,
      operand2: 95,
      operation: '\u00D7',
      answer: 9025,
    },
    {
      type: 'practice',
      prompt: 'What is 55\u00B2?',
      operand1: 55,
      operand2: 55,
      operation: '\u00D7',
      answer: 3025,
    },
    {
      type: 'quiz',
      question: 'What is the first step for 65\u00B2?',
      options: ['6 \u00D7 5', '6 \u00D7 7', '65 \u00D7 2', '6 + 5'],
      correctIndex: 1,
      explanation: 'Take 6, multiply by the next number up: 6 \u00D7 7 = 42, then append 25 \u2192 4225',
    },
  ],
};
